import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Verifier {

    private static Scanner firstScanner;
    private static Scanner secondScanner;
    private static File firstFile;
    private static File secondFile;

    public static void main(String args[]) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("This is a verifier program where you can compare the stripped" +
                " text output file generated by a human with a" +
                " stripped text output file generated by the stripper program \n");


        System.out.println("Please type the name of the first file for comparison ");
        String firstFileStr = scanner.next();
        System.out.println("Please type the name of the second file for comparison ");
        String secondFileSt = scanner.next();


        try {
            firstFile = new File(firstFileStr);
            secondFile = new File(secondFileSt);
            firstScanner = new Scanner(firstFile);
            secondScanner = new Scanner(secondFile);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        boolean result = compareFiles();

        if (result) {
            System.out.println("Files are identical :)");
        } else {
            System.out.println("Files are not identical :(");
        }

    }

    private static boolean compareFiles() {
        while (firstScanner.hasNext() && secondScanner.hasNext()) {
            if (firstScanner.nextLine().equals(secondScanner.nextLine())) {
                continue;
            } else {
                return false;
            }
        }
        return true;
    }
}